// Generated by scripts/build-sw.mjs at build time — do not hand-edit, it will be
// overwritten on the next build. Edit that script instead.
const CACHE = "sl-durian-522badd483";
const PRECACHE = [
  "assets/index-CQ3nFwfg.js",
  "assets/index-l7iWuPCP.css",
  "fonts.css",
  "icon-180.png",
  "icon-192.png",
  "icon-512.png",
  "index.html",
  "logo-full.jpg",
  "logo-mark.png",
  "manifest.json"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

// Cache-first: an offline market stall has no signal, so we never want to block on
// the network for anything we already have. Anything fetched that wasn't precached
// (e.g. an extra Chinese glyph subset from Google Fonts, only reachable while online)
// gets stored for next time. Navigations fall back to the shell if both cache and
// network miss, so a bookmarked URL still opens the app offline.
self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.ok && (res.type === "basic" || res.type === "cors")) {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return res;
        })
        .catch(() => {
          if (req.mode === "navigate") return caches.match("index.html");
          throw new Error("offline and not cached: " + req.url);
        });
    })
  );
});
