// Runs after `vite build`. Vite content-hashes its output filenames, so the
// service worker's precache list has to be generated post-build to reference the
// files that actually shipped — a static, hand-written list would go stale the
// moment a rebuild changes a hash. The *behaviour* (cache-first, offline shell) is
// still a plain, readable, hand-written service worker; only the file list and cache
// version are computed here.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const dist = path.join(root, "dist");

function walk(dir, base = dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(full, base));
    } else {
      out.push(path.relative(base, full).split(path.sep).join("/"));
    }
  }
  return out;
}

const allFiles = walk(dist).filter((f) => f !== "sw.js" && !f.startsWith(".vite/"));

// Fonts are already content-addressed by our own filenames (weight+index) and don't
// change unless the font subset itself changes, but everything else — the JS/CSS
// bundle and every static public/ asset — is small enough to just precache in full.
const precache = allFiles.sort();

const hash = crypto.createHash("sha1").update(precache.join(",")).digest("hex").slice(0, 10);
const cacheName = `sl-durian-${hash}`;

const sw = `// Generated by scripts/build-sw.mjs at build time — do not hand-edit, it will be
// overwritten on the next build. Edit that script instead.
const CACHE = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

// Cache-first: an offline market stall has no signal, so we never want to block on
// the network for anything we already have. Anything fetched that wasn't precached
// (e.g. an extra Chinese glyph subset from Google Fonts, only reachable while online)
// gets stored for next time. Navigations fall back to the shell if both cache and
// network miss, so a bookmarked URL still opens the app offline.
self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.ok && (res.type === "basic" || res.type === "cors")) {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return res;
        })
        .catch(() => {
          if (req.mode === "navigate") return caches.match("index.html");
          throw new Error("offline and not cached: " + req.url);
        });
    })
  );
});
`;

fs.writeFileSync(path.join(dist, "sw.js"), sw);
console.log(`wrote dist/sw.js — cache ${cacheName}, ${precache.length} precached files`);
